---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: aiprt-rest-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    # apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: aiprt-rest-service
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: aiprt-rest-service
    tanzu.app.live.view.application.actuator.port: "9090"
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  build:
    env:
    - name: DOTNET_CLI_TELEMETRY_OPTOUT
      value: "true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/swagger/v1/swagger.json"  # The path to the api documentation
      owner: aiprt-team
      system: ai-analysis-system
      description: Rest_Svc
  env:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: "true"

  source:
    git:
      url: https://github.com/trevorputbrese/csharp-rest-service
      ref:
        branch: main

  serviceClaims:
    - name: database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: customer-database
